name: projpred_workflow
channels:
 - conda-forge
 - bioconda
 - defaults
dependencies:
 - r-base
 - rstudio
 - r-brms
 - r-dplyr
 - r-devtools
 - r-matrix
 - r-mass
 - r-geomtextpath
 - r-latex2exp
 - r-vroom
 - r-microbenchmark
 - r-reshape2
 - r-tictoc
 - r-cowplot
 - r-philentropy
 - r-r.matlab
 - r-vgam