name: projpred_workflow
channels:
 - conda-forge
dependencies:
 - r-base=4.0.5
 - rstudio
 - r-brms
 - r-tidyverse
 - r-devtools
 - r-matrix
 - r-mass
 - r-geomtextpath
 - r-latex2exp
 - r-vroom
 - r-microbenchmark
 - r-reshape2
 - r-tictoc
 - r-cowplot